'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tb_empleado
    Public Property id As Integer
    Public Property nombres As String
    Public Property apellidos As String
    Public Property id_tipo_identificacion As Integer
    Public Property numero_identificacion As String
    Public Property fecha_ingreso As Date
    Public Property salario_base_mensual As Decimal
    Public Property direccion As String

End Class
